#pragma once

enum  ShapeType
{
	TRIANGLE, PLANE, CUBE, SPEHERE, SKYBOX, LINE, TERRAIN, CUSTOM
};
enum LightType
{
	DEFAULT = 0,
	DIRECTIONAL = 1,
	POINT = 2,
	SPOTLIGHT = 3,
	NONELIGHT = 4,
};

enum SourceShapeType
{
	SHAPE = 0,
	LIGHT = 1,
	PARTICLE = 2,
	PRIMITIVE = 3,
	NO_TYPE
};

enum Shading
{
	FORWARD_SHADING = 0,
	DEFFERED_SHADING = 1,
	ONLY_COLOR = 2,
	TEXTURE_COLOR = 3,
	DISPLACEMENT = 4,
	CUBEMAP = 5,
	HDR_SHADING = 6
}; // by bytes to-do

enum class CamView
{
	STATIC = 0, DYNAMIC = 1, MOVABLE = 2
};

enum class ShapeState
{
	CREATING, EXISTING, NOT_EXISTING
};

enum Direction
{
	UP, DOWN, LEFT, RIGHT, FORWARD, BACKWARD
};
enum FrameBufferType
{
	POSTPROCESSING = 1, BLUR = 2, HDR = 4, DEPTHMAP = 8, GBUFFER = 16, GAUSSIAN_HORIZONTAL = 32, GAUSSIAN_VERTICAL = 64, COLOR = 128, MAIN = 0
};